---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: eks-hpa-profile
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./monitoring-system    # path in repo
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-hpa-profile

